version: '3.7'

services:
  database:
    container_name: database
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=amcef
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ~/amcef/postgres/pgdata:/var/lib/postgresql/data/pgdata
